version: '3.7'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    command: --port 3443
    expose:
      - 3443
  
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app  
